
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry urlAddress;

	private global::Gtk.Button connectBtn;

	private global::Gtk.Button disconnectBtn;

	private global::Gtk.VBox vbox5;

	private global::Gtk.ScrolledWindow messageWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label2;

	private global::Gtk.Entry channelName;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label3;

	private global::Gtk.Entry message;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label4;

	private global::Gtk.Entry echo;

	private global::Gtk.Button button3;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Address URL");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.urlAddress = new global::Gtk.Entry();
		this.urlAddress.CanFocus = true;
		this.urlAddress.Name = "urlAddress";
		this.urlAddress.IsEditable = true;
		this.urlAddress.InvisibleChar = '●';
		this.hbox1.Add(this.urlAddress);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.urlAddress]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.connectBtn = new global::Gtk.Button();
		this.connectBtn.CanFocus = true;
		this.connectBtn.Name = "connectBtn";
		this.connectBtn.UseUnderline = true;
		this.connectBtn.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox1.Add(this.connectBtn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.connectBtn]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.disconnectBtn = new global::Gtk.Button();
		this.disconnectBtn.CanFocus = true;
		this.disconnectBtn.Name = "disconnectBtn";
		this.disconnectBtn.UseUnderline = true;
		this.disconnectBtn.Label = global::Mono.Unix.Catalog.GetString("Disconnect");
		this.hbox1.Add(this.disconnectBtn);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.disconnectBtn]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.messageWindow = new global::Gtk.ScrolledWindow();
		this.messageWindow.CanFocus = true;
		this.messageWindow.Name = "messageWindow";
		this.messageWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.messageWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.messageWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child messageWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.messageWindow.Add(this.textview1);
		this.vbox5.Add(this.messageWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.messageWindow]));
		w7.Position = 0;
		this.vbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox5]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Channel");
		this.vbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.channelName = new global::Gtk.Entry();
		this.channelName.CanFocus = true;
		this.channelName.Name = "channelName";
		this.channelName.IsEditable = true;
		this.channelName.WidthChars = 15;
		this.channelName.InvisibleChar = '●';
		this.vbox2.Add(this.channelName);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.channelName]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.hbox2.Add(this.vbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Message");
		this.vbox3.Add(this.label3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.message = new global::Gtk.Entry();
		this.message.CanFocus = true;
		this.message.Name = "message";
		this.message.IsEditable = true;
		this.message.WidthChars = 50;
		this.message.InvisibleChar = '●';
		this.vbox3.Add(this.message);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.message]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Subscribe");
		this.hbox3.Add(this.button4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Unsubscribe");
		this.hbox3.Add(this.button5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Publish");
		this.hbox3.Add(this.button6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button6]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Echo message");
		this.hbox4.Add(this.label4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.echo = new global::Gtk.Entry();
		this.echo.CanFocus = true;
		this.echo.Name = "echo";
		this.echo.IsEditable = true;
		this.echo.InvisibleChar = '●';
		this.hbox4.Add(this.echo);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.echo]));
		w22.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Emit");
		this.hbox4.Add(this.button3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button3]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 4;
		w25.Expand = false;
		w25.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 646;
		this.DefaultHeight = 476;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.connectBtn.Released += new global::System.EventHandler(this.OnConnectBtn);
		this.disconnectBtn.Released += new global::System.EventHandler(this.OnDisconnectBtn);
		this.button4.Released += new global::System.EventHandler(this.OnSubscribeBtn);
		this.button5.Released += new global::System.EventHandler(this.OnUnsubscribeBtn);
		this.button6.Released += new global::System.EventHandler(this.OnPublishBtn);
		this.button3.Released += new global::System.EventHandler(this.OnEmitBtn);
	}
}
